/**
 * Theme configurations for the SaaS template.
 */
export const THEMES = {
  light: {
    id: 'light',
    name: 'Clean Light',
    color: '#ffffff',
    bg: 'bg-white',
    text: 'text-slate-900',
    accent: 'bg-indigo-600',
    accentText: 'text-indigo-600',
    card: 'bg-slate-50',
    border: 'border-slate-200',
    muted: 'text-slate-500',
    footerBg: 'bg-slate-50',
  },
  dark: {
    id: 'dark',
    name: 'Deep Slate',
    color: '#0f172a',
    bg: 'bg-slate-950',
    text: 'text-slate-50',
    accent: 'bg-indigo-500',
    accentText: 'text-indigo-400',
    card: 'bg-slate-900',
    border: 'border-slate-800',
    muted: 'text-slate-400',
    footerBg: 'bg-slate-900',
  },
  vibrant: {
    id: 'vibrant',
    name: 'Vibrant Purple',
    color: '#6366f1',
    bg: 'bg-indigo-950',
    text: 'text-white',
    accent: 'bg-fuchsia-500',
    accentText: 'text-fuchsia-300',
    card: 'bg-white/10 backdrop-blur-md',
    border: 'border-white/20',
    muted: 'text-indigo-200',
    footerBg: 'bg-indigo-900/40',
  },
  emerald: {
    id: 'emerald',
    name: 'Midnight Emerald',
    color: '#064e3b',
    bg: 'bg-emerald-950',
    text: 'text-emerald-50',
    accent: 'bg-teal-500',
    accentText: 'text-teal-400',
    card: 'bg-emerald-900/50 backdrop-blur-sm',
    border: 'border-emerald-800',
    muted: 'text-emerald-300',
    footerBg: 'bg-emerald-900/40',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Rose',
    color: '#4c0519',
    bg: 'bg-rose-950',
    text: 'text-rose-50',
    accent: 'bg-orange-500',
    accentText: 'text-orange-400',
    card: 'bg-rose-900/40 backdrop-blur-sm',
    border: 'border-rose-800',
    muted: 'text-rose-200',
    footerBg: 'bg-rose-900/40',
  },
};

export type ThemeId = keyof typeof THEMES;
